BEGIN;

CREATE TABLE PATRON (
	PAT_ID		NUMERIC(10, 0) PRIMARY KEY,
    PAT_FNAME	VARCHAR(20) NOT NULL,
    PAT_LNAME	VARCHAR(20) NOT NULL,
    PAT_TYPE	VARCHAR(10) NOT NULL
);

CREATE TABLE BOOK (
	BOOK_NUM		NUMERIC(10, 0) PRIMARY KEY,
    BOOK_TITLE		VARCHAR(120) NOT NULL,
    BOOK_YEAR		NUMERIC(4),
    BOOK_COST		NUMERIC(8, 2),
    BOOK_SUBJECT	VARCHAR(120),
    PAT_ID			NUMERIC(10),
    FOREIGN KEY(PAT_ID) REFERENCES PATRON(PAT_ID)
);

CREATE TABLE CHECKOUT (
	CHECK_NUM		NUMERIC(15) PRIMARY KEY,
    BOOK_NUM		NUMERIC(10),
    PAT_ID			NUMERIC(10),
    CHECK_OUT_DATE	DATE,
    CHECK_DUE_DATE	DATE,
    CHECK_IN_DATE	DATE,
    FOREIGN KEY (BOOK_NUM) REFERENCES BOOK(BOOk_NUM),
    FOREIGN KEY (PAT_ID) REFERENCES PATRON(PAT_ID)
);

CREATE TABLE WRITES (
	BOOK_NUM	NUMERIC(10),
    AU_ID		NUMERIC(7),
    CONSTRAINT WRITES_BOOK_AU_PK PRIMARY KEY (BOOK_NUM, AU_ID),
    CONSTRAINT WRITES_BOOK_NUM_FK FOREIGN KEY (BOOK_NUM) REFERENCES BOOK(BOOK_NUM),
    CONSTRAINT WRITES_AU_ID_FK FOREIGN KEY (AU_ID) REFERENCES AUTHOR(AU_ID)
);

COMMIT;