SELECT
    LGBRAND.BRAND_ID,
    BRAND_NAME,
    ROUND(AVG(PROD_PRICE), 2) AS AVGPRICE
FROM LGPRODUCT
JOIN LGBRAND ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY LGBRAND.BRAND_ID
ORDER BY BRAND_NAME;