SELECT
    LGEMPLOYEE.EMP_NUM,
    EMP_FNAME,
    EMP_LNAME,
    MAX(SAL_AMOUNT) AS LARGESTSALARY
FROM LGEMPLOYEE
JOIN LGSALARY_HISTORY ON LGSALARY_HISTORY.EMP_NUM = LGEMPLOYEE.EMP_NUM
WHERE DEPT_NUM = 200
GROUP BY LGEMPLOYEE.EMP_NUM
ORDER BY LARGESTSALARY DESC;