SELECT
    LGDEPARTMENT.DEPT_NUM,
    DEPT_NAME,
    DEPT_PHONE,
    LGEMPLOYEE.EMP_NUM,
    EMP_LNAME
FROM LGDEPARTMENT
JOIN LGEMPLOYEE ON LGEMPLOYEE.EMP_NUM = LGDEPARTMENT.EMP_NUM
ORDER BY DEPT_NAME;