SELECT
    LGVENDOR.VEND_ID,
    VEND_NAME,
    BRAND_NAME,
    COUNT(LGPRODUCT.PROD_SKU) AS NUMPRODUCTS
FROM LGVENDOR
JOIN LGSUPPLIES ON LGSUPPLIES.VEND_ID = LGVENDOR.VEND_ID
JOIN LGPRODUCT ON LGPRODUCT.PROD_SKU = LGSUPPLIES.PROD_SKU
JOIN LGBRAND ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
GROUP BY
    LGBRAND.BRAND_ID,
    LGVENDOR.VEND_ID
ORDER BY
    VEND_NAME,
    BRAND_NAME;