SELECT
    LGBRAND.BRAND_ID,
    BRAND_NAME,
    BRAND_TYPE,
    AVG_PRICE
FROM (
    SELECT
        BRAND_ID,
        ROUND(AVG(PROD_PRICE), 2) AS AVG_PRICE
    FROM LGPRODUCT
    GROUP BY BRAND_ID
) AS AVERAGES
JOIN LGBRAND ON LGBRAND.BRAND_ID = AVERAGES.BRAND_ID
ORDER BY AVG_PRICE DESC
LIMIT 1;