SELECT
    LGINVOICE.INV_NUM,
    SEALER.LINE_NUM AS 'LINE_NUM(S)',
    SEALER.PROD_SKU AS 'PROD_SKU(S)',
    SEALER.PROD_DESCRIPT AS 'PROD_DESCRIPT(S)',
    TOP_COAT.LINE_NUM AS 'LINE_NUM(T)',
    TOP_COAT.PROD_SKU AS 'PROD_SKU(T)',
    TOP_COAT.PROD_DESCRIPT AS 'PROD_DESCRIPT(T)',
    SEALER.BRAND_ID
FROM LGINVOICE
JOIN (
    SELECT
        LGINVOICE.INV_NUM,
        LINE_NUM,
        LGPRODUCT.PROD_SKU,
        PROD_DESCRIPT,
        BRAND_ID
    FROM LGINVOICE
    JOIN LGLINE ON LGLINE.INV_NUM = LGINVOICE.INV_NUM
    JOIN LGPRODUCT ON LGPRODUCT.PROD_SKU = LGLINE.PROD_SKU
    WHERE PROD_CATEGORY = 'Sealer'
) AS SEALER ON SEALER.INV_NUM = LGINVOICE.INV_NUM
JOIN (
    SELECT
        LGINVOICE.INV_NUM,
        LINE_NUM,
        LGPRODUCT.PROD_SKU,
        PROD_DESCRIPT,
        BRAND_ID
    FROM LGINVOICE
    JOIN LGLINE ON LGLINE.INV_NUM = LGINVOICE.INV_NUM
    JOIN LGPRODUCT ON LGPRODUCT.PROD_SKU = LGLINE.PROD_SKU
    WHERE PROD_CATEGORY = 'Top Coat'
) AS TOP_COAT ON TOP_COAT.INV_NUM = LGINVOICE.INV_NUM
WHERE SEALER.BRAND_ID = TOP_COAT.BRAND_ID
ORDER BY
    LGINVOICE.INV_NUM,
    SEALER.LINE_NUM,
    TOP_COAT.LINE_NUM DESC;