SELECT
    LGEMPLOYEE.EMP_NUM AS 'Emp_Num',
    EMP_LNAME AS 'Emp_LName',
    EMP_FNAME AS 'Emp_FName',
    EMP_EMAIL AS 'Emp_Email',
    COUNT(PRODUCTS.PROD_SKU) AS 'Total'
FROM (
    SELECT
        EMPLOYEE_ID,
        LGPRODUCT.PROD_SKU
    FROM LGLINE
    JOIN LGINVOICE ON LGINVOICE.INV_NUM = LGLINE.INV_NUM
    JOIN LGPRODUCT ON LGPRODUCT.PROD_SKU = LGLINE.PROD_SKU
    JOIN LGBRAND ON LGBRAND.BRAND_ID = LGPRODUCT.BRAND_ID
    WHERE BRAND_NAME = 'BINDER PRIME'
    AND INV_DATE BETWEEN '2017-11-1' AND '2017-12-5'
) AS PRODUCTS
JOIN LGEMPLOYEE ON LGEMPLOYEE.EMP_NUM = PRODUCTS.EMPLOYEE_ID
GROUP BY EMPLOYEE_ID
ORDER BY Total DESC, EMP_LNAME;
-- This one looks to be incorrect but I cant seem to get it to work