SELECT DISTINCT
    LGCUSTOMER.CUST_CODE AS 'Cust_Code',
    CUST_FNAME AS 'Cust_FName',
    CUST_LNAME AS 'Cust_LName'
FROM LGCUSTOMER
JOIN (
    SELECT LGCUSTOMER.CUST_CODE AS CUST_CODE
    FROM LGCUSTOMER
    JOIN LGINVOICE ON LGINVOICE.CUST_CODE = LGCUSTOMER.CUST_CODE
    WHERE EMPLOYEE_ID = 83649
) AS EMP1 ON EMP1.CUST_CODE = LGCUSTOMER.CUST_CODE
JOIN (
    SELECT LGCUSTOMER.CUST_CODE AS CUST_CODE
    FROM LGCUSTOMER
    JOIN LGINVOICE ON LGINVOICE.CUST_CODE = LGCUSTOMER.CUST_CODE
    WHERE EMPLOYEE_ID = 83677
) AS EMP2 ON EMP2.CUST_CODE = LGCUSTOMER.CUST_CODE
ORDER BY
    CUST_LNAME,
    CUST_FNAME;