SELECT
    LGCUSTOMER.CUST_CODE,
    CUST_FNAME,
    CUST_LNAME,
    CUST_STREET,
    CUST_CITY,
    CUST_STATE,
    CUST_ZIP,
    INV_DATE,
    PURCHASE AS 'Largest Invoice'
FROM (
    SELECT
        LGCUSTOMER.CUST_CODE,
        INV_DATE,
        ROUND(MAX(INV_TOTAL), 2) AS PURCHASE
    FROM LGINVOICE
    RIGHT JOIN LGCUSTOMER ON LGCUSTOMER.CUST_CODE = LGINVOICE.CUST_CODE
    GROUP BY LGCUSTOMER.CUST_CODE
) AS MAX_PURCHASE
JOIN LGCUSTOMER ON LGCUSTOMER.CUST_CODE = MAX_PURCHASE.CUST_CODE
WHERE CUST_STATE = 'AL'
ORDER BY
    CUST_LNAME,
    CUST_FNAME;
-- I couldn't get it to show 0 instead of null for LARGEST INVOICE if ther was no invoices