SELECT
    BOOK.BOOK_NUM,
    BOOK_TITLE,
    BOOK_SUBJECT,
    AU_LNAME,
    AMOUNT AS 'Num Books by Author'
FROM WRITES
JOIN BOOK ON WRITES.BOOK_NUM = BOOK.BOOK_NUM
JOIN AUTHOR ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN (
    SELECT
        AU_ID,
        COUNT(BOOK_NUM) AS AMOUNT
    FROM WRITES
    GROUP BY AU_ID
) AS WRITTEN ON AUTHOR.AU_ID = WRITTEN.AU_ID
WHERE BOOK_SUBJECT = 'Cloud'
ORDER BY
    BOOK_TITLE,
    AU_LNAME;