SELECT
    LGEMPLOYEE.EMP_NUM,
    EMP_LNAME,
    EMP_FNAME,
    SAL_FROM,
    SAL_END,
    SAL_AMOUNT
FROM LGSALARY_HISTORY
JOIN LGEMPLOYEE ON LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM
WHERE LGEMPLOYEE.EMP_NUM IN (83731, 83745, 84039)
ORDER BY
    LGEMPLOYEE.EMP_NUM,
    SAL_FROM;