SELECT DISTINCT
    CUST_FNAME,
    CUST_LNAME,
    CUST_STREET,
    CUST_CITY,
    CUST_STATE,
    CUST_ZIP
FROM LGBRAND
JOIN LGPRODUCT ON LGPRODUCT.BRAND_ID = LGBRAND.BRAND_ID
JOIN LGLINE ON LGLINE.PROD_SKU = LGPRODUCT.PROD_SKU
JOIN LGINVOICE ON LGINVOICE.INV_NUM = LGLINE.INV_NUM
JOIN LGCUSTOMER ON LGCUSTOMER.CUST_CODE = LGINVOICE.CUST_CODE
WHERE LGBRAND.BRAND_NAME = 'FORESTERS BEST'
AND LGPRODUCT.PROD_CATEGORY = 'Top Coat'
AND LGINVOICE.INV_DATE BETWEEN '2017-7-15' AND '2017-7-31'
ORDER BY
    CUST_STATE,
    CUST_LNAME,
    CUST_FNAME;