SELECT
    AU_LNAME,
    AU_FNAME,
    BOOK_TITLE,
    BOOK_COST
FROM BOOK
JOIN WRITES ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
JOIN AUTHOR ON WRITES.AU_ID = AUTHOR.AU_ID
ORDER BY
    BOOK.BOOK_NUM,
    AUTHOR.AU_ID;