SELECT
    BOOK.BOOK_NUM,
    BOOK_TITLE,
    AU_LNAME,
    AU_FNAME,
    PATRON.PAT_ID,
    PAT_LNAME,
    PAT_TYPE
FROM BOOK
JOIN WRITES ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
JOIN AUTHOR ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN PATRON ON BOOK.PAT_ID = PATRON.PAT_ID
ORDER BY
    BOOK_TITLE;