SELECT
    BOOK.BOOK_NUM,
    BOOK_TITLE,
    COUNT(CHECK_NUM) AS 'Times Checked Out'
FROM BOOK
LEFT JOIN CHECKOUT ON BOOK.BOOK_NUM = CHECKOUT.BOOK_NUM
GROUP BY
    BOOK.BOOK_NUM,
    BOOK_TITLE
ORDER BY
    COUNT(CHECK_NUM) DESC,
    BOOK_TITLE;