SELECT
    PATRON.PAT_ID,
    PAT_LNAME,
    COUNT(CHECK_NUM) AS 'NUM CHECKOUTS',
    COUNT(DISTINCT CHECKOUT.BOOK_NUM) AS 'NUM DIFFERENT CHECKOUTS'
FROM CHECKOUT
JOIN PATRON ON PATRON.PAT_ID = CHECKOUT.PAT_ID
JOIN BOOK ON BOOK.BOOK_NUM = CHECKOUT.BOOK_NUM
GROUP BY CHECKOUT.PAT_ID
HAVING COUNT(CHECK_NUM) >= 3
ORDER BY
    COUNT(DISTINCT CHECKOUT.BOOK_NUM) DESC,
    COUNT(CHECK_NUM) DESC,
    PATRON.PAT_ID;