SELECT
    PAT_ID,
    ROUND(AVG(datediff(CHECK_IN_DATE, CHECK_OUT_DATE)), 2) AS 'Average Days Kept'
FROM CHECKOUT
GROUP BY PAT_ID
HAVING COUNT(CHECK_NUM) >= 3
ORDER BY ROUND(AVG(datediff(CHECK_IN_DATE, CHECK_OUT_DATE)), 2) DESC;